spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/db_payments?useSSL=false
    username: fazt
    password: 123456

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html
